# =============================================================================
# registry_environment_blocks_longitudinal.R - registry rows for the
# BLOCK x PERIOD environmental indicators.
#
# GENERATED by cfi-environdata/python/blocks/make_block_registry.py. Edit the
# generator, not this file.
#
# Source: cfi-environdata/data/output/blocks/all_block_indicators_longitudinal.csv
# — 51,417 blocks x 16 periods of 45 days spanning 2024-07-31 to 2026-07-21.
# Column detail and caveats: that repo's
# data/output/blocks/block_data_dictionary.md
#
# A THIRD UNIT OF ANALYSIS. registry_environment.R describes BUSINESSES,
# registry_environment_blocks.R describes BLOCKS, and these describe
# BLOCK-PERIODS. Never mix them in one estimate. An indicator sharing a name
# across the three is not the same quantity: a 150m buffer around a business,
# the block containing it, and that block during one 45-day window are three
# different regions of space-time.
#
# HOW TO MERGE. JOIN ON city + block_id + period_index. `block_id` is the RAW
# grid id matching final_sampling_grid_2026.geojson and enum_data's BlockID; it
# restarts at 1 in every city, so a join on it alone fans rows out.
#
# READ THIS TABLE ALONG THE TIME AXIS. It exists because three of these
# indicators — rainfall, ERA5 heat stress and AOD — were EXCLUDED from the
# static block table for low SPATIAL variation, and carry large TEMPORAL
# variation instead (Lagos rainfall 11-594mm across periods, AOD 0.24-0.81).
# Only lst_max_c approaches block scale; rainfall is 5.5km (~37 blocks wide) and
# ERA5 heat stress 11km (~74 blocks). For spatial pattern use the static table.
#
# THE *_valid_obs COLUMNS ARE NOT ONLY DIAGNOSTICS here. Clear-sky coverage is
# itself seasonal, so a period with few observations is a statement about that
# season. Check them before comparing lst_* or aod_mean across periods.
#
# NOT REGISTERED (and why):
#   block_id       join key (with city and period_index)
#   block_uid      city-prefixed unique block key
#   city           already a GROUPS entry in registry.R
#   period_index   join key; the time dimension itself
#   period_start   period bound, descriptive
#   period_end     period bound, descriptive
#
# TO USE: source after registry.R and keep SEPARATE from both other registries
# unless the app can distinguish units of analysis.
# =============================================================================

REGISTRY_ENVIRONMENT_BLOCKS_LONGITUDINAL <- tribble(
  ~id, ~label, ~domain, ~type, ~source_q, ~source_col, ~notes, ~description,
  "lst_max_c", "Maximum land surface temperature (C)", "envlong_heat", "continuous", NA, "lst_max_c", "GEE: MODIS/061/MOD11A1, 1km | per 45-day period", "Highest daytime land surface temperature in the block during this period. Surface temperature, not air temperature. ~25% missing overall, which is SEASONAL CLOUD and itself informative: coverage falls to 46-57% in Dec-Mar and Oct-Jan against 84-99% otherwise, and by city runs Addis Ababa 100%, Jakarta 65%, Lagos 62%. Check lst_valid_obs before reading a period's value.",
  "lst_mean_c", "Mean land surface temperature (C)", "envlong_heat", "continuous", NA, "lst_mean_c", "GEE: MODIS/061/MOD11A1, 1km | per 45-day period", "Mean daytime land surface temperature in the block during this period. Same seasonal cloud gaps as lst_max_c.",
  "lst_valid_obs", "Clear-sky observations", "envlong_heat", "continuous", NA, "lst_valid_obs", "Diagnostic, but ALSO a seasonal signal", "Number of clear-sky MODIS observations in this block-period, of up to 45. Unlike most diagnostics this carries real information: a period with few observations is a CLOUDY period, so the column doubles as a wet-season indicator. Always check it before comparing lst_* across periods.",
  "rain_total_mm", "Total rainfall (mm)", "envlong_rain", "continuous", NA, "rain_total_mm", "GEE: UCSB-CHC/CHIRPS/V3/DAILY_SAT, 5.5km | per 45-day period", "Total precipitation in the block during this period. THE STRONGEST SEASONAL SIGNAL IN THE DATASET: Lagos ranges 11 to 594mm across the 16 periods. Rainfall was excluded from the static block table for low spatial variation (4-13% within-city) and appears here precisely because its temporal variation is so large. At 5.5km — about 37 blocks wide — read it along the TIME axis, not as spatial pattern.",
  "rain_days_dry", "Dry days (<1mm)", "envlong_rain", "continuous", NA, "rain_days_dry", "GEE: CHIRPS | WMO dry-day threshold | per 45-day period", "Days in this 45-day period with rainfall below 1mm, the WMO convention for a day without meaningful rain. Directly comparable across periods and cities: CHIRPS is gap-filled, so every block-period has all 45 days.",
  "rain_max_day_mm", "Wettest day (mm)", "envlong_rain", "continuous", NA, "rain_max_day_mm", "GEE: CHIRPS | per 45-day period", "Highest single-day rainfall in this period — the extreme-event measure rather than the accumulation.",
  "aod_mean", "Mean aerosol optical depth", "envlong_air", "continuous", NA, "aod_mean", "GEE: MODIS/061/MCD19A2_GRANULES, 1km | per 45-day period", "Mean aerosol optical depth in the block during this period, the standard satellite proxy for particulate pollution. STRONGLY SEASONAL: Lagos ranges 0.24 to 0.81 across periods, peaking in the Harmattan dust season, a swing far larger than its spatial variation (which is why AOD is absent from the static block table). ~6% missing from cloud screening.",
  "aod_valid_obs", "Valid AOD retrievals", "envlong_air", "continuous", NA, "aod_valid_obs", "Diagnostic, but also a cloudiness signal", "Number of valid MAIAC retrievals in this block-period. Like lst_valid_obs it is partly a seasonal cloud indicator, and should be checked before comparing aod_mean across periods.",
  "ntl_mean_radiance", "Nighttime radiance", "envlong_light", "continuous", NA, "ntl_mean_radiance", "GEE: NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG, 500m | per 45-day period", "Mean nighttime radiance in the block during this period. NOTE VIIRS composites are MONTHLY, so a 45-day period contains only 1-2 of them — this is the coarsest series here in TIME as well as being coarse in space. A proxy for economic activity at neighbourhood scale, not for any individual business.",
  "wbgt_mean_c", "Heat stress index (sWBGT, C)", "envlong_heatstress", "continuous", NA, "wbgt_mean_c", "Derived from ECMWF/ERA5_LAND, 11km | per 45-day period | CITY-SCALE", "Mean simplified Wet Bulb Globe Temperature in this block-period, combining air temperature and humidity. ERA5 heat stress was excluded from the static block table for near-zero within-city variance and appears here for its seasonality (Lagos 28.6 to 32.6C across periods). AT 11km THIS IS ~74 BLOCKS WIDE - read it along TIME, not space - though it is NOT constant within a city either: 61-249 distinct values per city-period, with up to 2.47C spread across Addis Ababa, since the grid spans 2-3 cells and picks up elevation. Missing for 1,473 Lagos blocks in every period (Lagos Island, Victoria Island and the lagoon, which ERA5-Land masks as water).",
  "rh_mean_pct", "Mean relative humidity (%)", "envlong_heatstress", "continuous", NA, "rh_mean_pct", "Derived from ERA5-Land temperature and dewpoint, 11km | per 45-day period", "Mean relative humidity in this block-period. The variable that makes heat dangerous, and the reason wbgt_mean_c ranks these cities differently from land surface temperature. Same 11km resolution caveat and the same Lagos lagoon gap as wbgt_mean_c.",
  "no2_mean", "Tropospheric NO2 (micromol/m2)", "envlong_air", "continuous", NA, "no2_mean", "GEE: COPERNICUS/S5P/OFFL/L3_NO2, ~1.1km | per 45-day period", "Mean tropospheric NO2 column density in this block-period. Specific to combustion - vehicles, generators, industry - where AOD mixes traffic with dust and biomass haze, and the two peak in different periods. Lagos ranges 30 to 90 across the window. A column density, not a surface concentration.",
) %>% mutate(frame = "Block-period")
